using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using FolkerKinzel.Strings.Intls;
using FolkerKinzel.Strings.Properties;

namespace FolkerKinzel.Strings;

/// <summary>
/// Combines the hash code for multiple character based values into a single persistent hash code.
/// </summary>
/// <param name="hashType">The type of hash code.</param>
/// 
/// 
/// <remarks>
/// <para>
/// <note type="important">
/// Keep in mind that this is a value type. Don't forget the <c>ref</c> keyword when passing instances
/// to other methods!
/// </note>
/// </para>
/// <para>
/// <note type="warning">
/// Never use the default constructor!
/// </note>
/// </para>
/// <para>
/// The method <see cref="string.GetHashCode()">String.GetHashCode()</see> returns a different
/// hash code for an identical string with each program run for security reasons. Apart
/// from the fact that the hash algorithm of <see cref="string.GetHashCode()">String.GetHashCode()</see>
/// could be different in different framework versions, it makes no sense to use the
/// return value of <see cref="string.GetHashCode()" /> for reuse. The alternatives, e.g.
/// <see cref="MD5" /> or <see cref="SHA256" />, use more storage space and are slower.
/// This struct offers a slim alternative that is suitable for hashing very short strings
/// that are not used in a security-critical context.
/// </para>
/// <para>
/// The hashcode generated by this method is not identical to the hashcode generated
/// by the .NET Framework 4.0, because it uses roundshifting to preserve more information.
/// </para>
/// <para>
/// The hashcodes generated with different values for <paramref name="hashType" /> may
/// provide different hashcodes for an identical Char sequence and MUST therefore not
/// be mixed.
/// </para>
/// <para>
/// Do not use the hashcodes generated by this method for security-critical purposes
/// (such as hashing passwords)!
/// </para>
/// </remarks>
/// 
/// <exception cref="ArgumentException"> <paramref name="hashType" /> is not a defined 
/// value of the <see cref="HashType" /> enum.</exception>
#if !(NET462 || NETSTANDARD2_0 || NETSTANDARD2_1 || NETCOREAPP3_1)
[SuppressMessage("Usage", "CA2231:Overload operator equals on overriding value type Equals",
    Justification = "PersistentStringHash is a mutable struct and should not be compared with other instances.")]
#endif
[StructLayout(LayoutKind.Auto)]
public struct PersistentStringHash(HashType hashType)
{
    private readonly HashType _hashType = hashType switch
    {
        HashType.Ordinal or HashType.OrdinalIgnoreCase or HashType.AlphaNumericIgnoreCase => hashType,
        _ => throw new ArgumentException(Res.UndefinedEnumValue, nameof(hashType)),
    };

    private const int INITIAL_VALUE = (5381 << 16) + 5381;
    private int _hash1 = INITIAL_VALUE;
    private int _hash2 = INITIAL_VALUE;
    private bool _odd = false;

    /// <summary>
    /// The type of hash code this instance computes.
    /// </summary>
    public readonly HashType HashType => _hashType;

    /// <summary>
    /// Calculates the final hash code after consecutive Add invocations.
    /// </summary>
    /// <returns>The calculated hash code.</returns>
    /// <remarks>
    /// <para>
    /// The method <see cref="string.GetHashCode()">String.GetHashCode()</see> returns a different
    /// hash code for an identical string with each program run for security reasons. Apart
    /// from the fact that the hash algorithm of <see cref="string.GetHashCode()">String.GetHashCode()</see>
    /// could be different in different framework versions, it makes no sense to use the
    /// return value of <see cref="string.GetHashCode()" /> for reuse. The alternatives, e.g.
    /// <see cref="MD5" /> or <see cref="SHA256" />, use more storage space and are slower.
    /// This method offers a slim alternative that is suitable for hashing very short strings
    /// that are not used in a security-critical context.
    /// </para>
    /// <para>
    /// The hashcode generated by this method is not identical to the hashcode generated
    /// by the .NET Framework 4.0, because it uses roundshifting to preserve more information.
    /// </para>
    /// <para>
    /// Do not use the hashcodes generated by this method for security-critical purposes
    /// (such as hashing passwords)!
    /// </para>
    /// </remarks>
    public readonly int ToHashCode()
    {
        unchecked { return _hash1 + (_hash2 * 1566083941); }
    }

    /// <summary>
    /// This method is not supported and should not be called.
    /// </summary>
    /// <param name="obj">Ignored</param>
    /// <returns>This method will always throw a <see cref="NotSupportedException"/>.</returns>
    /// <exception cref="NotSupportedException">This method is not supported.</exception>
    [Obsolete(
        $"""
        PersistentStringHash is a mutable struct and should not be compared with other instances.
        """, true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
#pragma warning disable CS0809 // Obsolete member overrides non-obsolete member
    public override readonly bool Equals([NotNullWhen(true)] object? obj) => throw new NotSupportedException();
#pragma warning restore CS0809 // Obsolete member overrides non-obsolete member

    /// <summary>
    /// This method is not supported and should not be called.
    /// </summary>
    /// <returns>This method will always throw a <see cref="NotSupportedException"/>.</returns>
    /// <exception cref="NotSupportedException">This method is not supported.</exception>
    [Obsolete(
        $"""
        PersistentStringHash is a mutable struct and should not be compared with other instances. 
        Use ToHashCode() to retrieve the computed hash code.
        """, true)]
    [EditorBrowsable(EditorBrowsableState.Never)]
#pragma warning disable CS0809 // Obsolete member overrides non-obsolete member
    public override readonly int GetHashCode() => throw new NotSupportedException();
#pragma warning restore CS0809 // Obsolete member overrides non-obsolete member

#if NETSTANDARD2_0 || NET462
    /// <summary>
    /// Adds the <see cref="char"/>-sequence of a <see cref="string"/> to the hash code.
    /// </summary>
    /// <param name="s">The <see cref="string"/>, or <c>null</c>.</param>
    /// <exception cref="InvalidOperationException">
    /// The instance had been initialized using the default constructor.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add(string? s) => Add(s.AsSpan());
#endif

    /// <summary>
    /// Adds the content of a read-only character span to the hash code.
    /// </summary>
    /// <param name="chars">A span of Unicode characters.</param>
    /// <exception cref="InvalidOperationException">
    /// The instance had been initialized using the default constructor.
    /// </exception>
    public void Add(ReadOnlySpan<char> chars)
    {
        if (chars.Length == 0)
        {
            return;
        }

        switch (_hashType)
        {
            case HashType.Ordinal:
                GetHashCodeOrdinal(chars);
                break;
            case HashType.OrdinalIgnoreCase:
                GetHashCodeOrdinalIgnoreCase(chars);
                break;
            case HashType.AlphaNumericIgnoreCase:
                GetHashCodeAlphaNumericNoCase(chars);
                break;
            default:
                throw new InvalidOperationException(Res.DefaultCtor);
        }
    }

    /// <summary>
    /// Adds a single character to the hash code.
    /// </summary>
    /// <param name="c">The <see cref="char"/> to hash.</param>
#if !NET462
    [SuppressMessage("Style", "IDE0302:Simplify collection initialization",
        Justification = "Performance: Collection expression allocates a new array.")]
#endif
    public void Add(char c)
     => Add(stackalloc char[] { c });

    /// <summary>
    /// Adds the content of a <see cref="StringBuilder"/> to the hash code.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> whose content is 
    /// hashed.</param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="builder"/> is <c>null</c>.
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// The instance had been initialized using the default constructor.
    /// </exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add(StringBuilder builder)
    {
        _ArgumentNullException.ThrowIfNull(builder, nameof(builder));
#if NETSTANDARD2_1 || NETSTANDARD2_0 || NET462
        DoAdd(builder, 0, builder.Length);
#else
        foreach (ReadOnlyMemory<char> chunk in builder.GetChunks())
        {
            Add(chunk.Span);
        }
#endif
    }

    /// <summary>
    /// Adds a sequence of characters from the content of a <see cref="StringBuilder"/>
    /// to the hash code that begins with <paramref name="startIndex"/> and reaches to 
    /// the end of <paramref name="builder"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> whose content is 
    /// hashed.</param>
    /// <param name="startIndex">The start index in <paramref name="builder"/>.</param>
    /// 
    /// <exception cref="ArgumentNullException">
    /// <paramref name="builder"/> is <c>null</c>.
    /// </exception>
    /// <exception cref="ArgumentOutOfRangeException"> <paramref name="startIndex" /> is
    /// less than zero or greater than the number of characters in <paramref name="builder"
    /// />.</exception>
    /// <exception cref="InvalidOperationException">
    /// The instance had been initialized using the default constructor.
    /// </exception>
    public void Add(StringBuilder builder, int startIndex)
    {
        _ArgumentNullException.ThrowIfNull(builder, nameof(builder));

        if ((uint)startIndex > (uint)builder.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(startIndex));
        }

        DoAdd(builder, startIndex, builder.Length - startIndex);
    }

    /// <summary>
    /// Adds a sequence of characters from the content of a <see cref="StringBuilder"/>
    /// to the hash code that begins with <paramref name="startIndex"/> and contains 
    /// <paramref name="count"/> characters.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> whose content is 
    /// hashed.</param>
    /// <param name="startIndex">The start index in <paramref name="builder"/>.</param>
    /// <param name="count">The number of characters to hash.</param>
    /// 
    /// <exception cref="ArgumentNullException">
    /// <paramref name="builder"/> is <c>null</c>.
    /// </exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// <para>
    /// <paramref name="startIndex" /> or <paramref name="count" /> are smaller than zero
    /// or larger than the number of characters in <paramref name="builder" />
    /// </para>
    /// <para>
    /// - or -
    /// </para>
    /// <para>
    /// <paramref name="startIndex" /> + <paramref name="count" /> is larger than the number
    /// of characters in <paramref name="builder" />.
    /// </para>
    /// </exception>
    /// <exception cref="InvalidOperationException">
    /// The instance had been initialized using the default constructor.
    /// </exception>
    public void Add(StringBuilder builder, int startIndex, int count)
    {
        _ArgumentNullException.ThrowIfNull(builder, nameof(builder));

        if ((uint)startIndex > (uint)builder.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(startIndex));
        }

        if ((uint)count > (uint)(builder.Length - startIndex))
        {
            throw new ArgumentOutOfRangeException(nameof(count));
        }

        DoAdd(builder, startIndex, count);
    }

#if NETSTANDARD2_0 || NET462
    /// <summary>
    /// Generates a persistent hash code for the characters of the specified <see cref="string"/> 
    /// using the specified <paramref name="hashType"/>.
    /// </summary>
    /// <param name="s">The <see cref="string"/> whose <see cref="char"/>-sequence is being hashed,
    /// or <c>null</c>.</param>
    /// <param name="hashType">The kind of hashcode to be generated.</param>
    /// <returns>The hashcode.</returns>
    /// <exception cref="ArgumentException"> <paramref name="hashType" /> is not a defined 
    /// value of the <see cref="HashType" /> enum.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int From(string? s, HashType hashType)
        => s.AsSpan().GetPersistentHashCode(hashType);
#endif

    /// <summary>
    /// Generates a persistent hash code for the characters in the specified read-only span
    /// using the specified <paramref name="hashType"/>.
    /// </summary>
    /// <param name="span">The <see cref="char"/>-sequence that is being hashed.</param>
    /// <param name="hashType">The kind of hashcode to be generated.</param>
    /// <returns>The hashcode.</returns>
    /// <exception cref="ArgumentException"> <paramref name="hashType" /> is not a defined 
    /// value of the <see cref="HashType" /> enum.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int From(ReadOnlySpan<char> span, HashType hashType)
        => span.GetPersistentHashCode(hashType);

    /// <summary>
    /// Generates a persistent hash code for the characters in the specified 
    /// <see cref="StringBuilder"/> using the specified <paramref name="hashType"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> whose <see cref="char"/>-sequence
    /// is being hashed.</param>
    /// <param name="hashType">The kind of hashcode to be generated.</param>
    /// <returns>The hashcode.</returns>
    /// <exception cref="ArgumentNullException"> <paramref name="builder" /> is <c>null</c>.</exception>
    /// <exception cref="ArgumentException"> <paramref name="hashType" /> is not a defined 
    /// value of the <see cref="HashType" /> enum.</exception>
    public static int From(StringBuilder builder, HashType hashType)
    {
        var hasher = new PersistentStringHash(hashType);
        hasher.Add(builder);
        return hasher.ToHashCode();
    }

    /// <summary>
    /// Generates a persistent hash code for the <see cref="char"/>-sequence in the specified 
    /// <see cref="StringBuilder"/> that begins with <paramref name="startIndex"/> and reaches to 
    /// the end of <paramref name="builder"/>, using the specified <paramref name="hashType"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> whose <see cref="char"/>-sequence
    /// is being hashed.</param>
    /// <param name="startIndex">The start index in <paramref name="builder"/>.</param>
    /// <param name="hashType">The kind of hashcode to be generated.</param>
    /// <returns>The hashcode.</returns>
    /// <exception cref="ArgumentNullException"> <paramref name="builder" /> is <c>null</c>.</exception>
    /// <exception cref="ArgumentOutOfRangeException"> <paramref name="startIndex" /> is
    /// less than zero or greater than the number of characters in <paramref name="builder"
    /// />.</exception>
    /// <exception cref="ArgumentException"> <paramref name="hashType" /> is not a defined 
    /// value of the <see cref="HashType" /> enum.</exception>
    public static int From(StringBuilder builder, int startIndex, HashType hashType)
    {
        var hasher = new PersistentStringHash(hashType);
        hasher.Add(builder, startIndex);
        return hasher.ToHashCode();
    }

    /// <summary>
    /// Generates a persistent hash code for the <see cref="char"/>-sequence in the specified 
    /// <see cref="StringBuilder"/> that begins with <paramref name="startIndex"/> and contains 
    /// <paramref name="count"/> characters, using the specified <paramref name="hashType"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> whose <see cref="char"/>-sequence
    /// is being hashed.</param>
    /// <param name="startIndex">The start index in <paramref name="builder"/>.</param>
    /// <param name="count">The number of characters to hash.</param>
    /// <param name="hashType">The kind of hashcode to be generated.</param>
    /// <returns>The hashcode.</returns>
    /// <exception cref="ArgumentNullException"> <paramref name="builder" /> is <c>null</c>.</exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// <para>
    /// <paramref name="startIndex" /> or <paramref name="count" /> are smaller than zero
    /// or larger than the number of characters in <paramref name="builder" />
    /// </para>
    /// <para>
    /// - or -
    /// </para>
    /// <para>
    /// <paramref name="startIndex" /> + <paramref name="count" /> is larger than the number
    /// of characters in <paramref name="builder" />.
    /// </para>
    /// </exception>
    /// <exception cref="ArgumentException"> <paramref name="hashType" /> is not a defined 
    /// value of the <see cref="HashType" /> enum.</exception>
    public static int From(StringBuilder builder, int startIndex, int count, HashType hashType)
    {
        var hasher = new PersistentStringHash(hashType);
        hasher.Add(builder, startIndex, count);
        return hasher.ToHashCode();
    }


#if NETSTANDARD2_1 || NETSTANDARD2_0 || NET462

    private void DoAdd(StringBuilder builder, int startIndex, int count)
    {
        if (count == 0)
        {
            return;
        }

        // Avoid copying of very short StringBuilder content: 
        if ((count - startIndex) <= StringBuilderExtension.SIMPLE_ALGORITHM_THRESHOLD)
        {
            DoAddSimple(builder, startIndex, startIndex + count);
            return;
        }

        using ArrayPoolHelper.SharedArray<char> shared = ArrayPoolHelper.Rent<char>(count);
        builder.CopyTo(startIndex, shared.Array, 0, count);
        Add(shared.Array.AsSpan(0, count));
    }

    private void DoAddSimple(StringBuilder builder, int startIndex, int end)
    {
        switch(_hashType)
        {
            case HashType.Ordinal:
                AddHashCodeOrdinalSimple(builder, startIndex, end);
                break;
            case HashType.OrdinalIgnoreCase:
                AddHashCodeOrdinalIgnoreCaseSimple(builder, startIndex, end);
                break;
            case HashType.AlphaNumericIgnoreCase:
                AddHashCodeAlphaNumericIgnoreCaseSimple(builder, startIndex, end);
                break;
            default:
                throw new InvalidOperationException(Res.DefaultCtor);
        }
    }

    private void AddHashCodeOrdinalSimple(StringBuilder sb, int startIndex, int end)
    {
        unchecked
        {
            if (_odd)
            {
                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ sb[startIndex++];
                _odd = false;
            }

            for (int i = startIndex; i < end; i += 2)
            {
                _hash1 = ((_hash1 << 5) + _hash1 + (_hash1 >> 27)) ^ sb[i];

                if (i == end - 1)
                {
                    _odd = true;
                    break;
                }

                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ sb[i + 1];
            }
        }
    }

    private void AddHashCodeOrdinalIgnoreCaseSimple(StringBuilder sb, int startIndex, int end)
    {
        unchecked
        {
            if (_odd)
            {
                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(sb[startIndex++]);
                _odd = false;
            }

            for (int i = startIndex; i < end; i += 2)
            {
                _hash1 = ((_hash1 << 5) + _hash1 + (_hash1 >> 27)) ^ char.ToUpperInvariant(sb[i]);

                if (i == end - 1)
                {
                    _odd = true;
                    break;
                }

                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(sb[i + 1]);
            }
        }
    }

    private void AddHashCodeAlphaNumericIgnoreCaseSimple(StringBuilder sb, int startIndex, int end)
    {
        unchecked
        {
            if (_odd)
            {
                for (int i = startIndex; i < end; i++)
                {
                    char c = sb[i];

                    if (char.IsLetterOrDigit(c))
                    {
                        _odd = false;
                        _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(c);
                        startIndex = i + 1;
                        break;
                    }
                }
            }

            for (int i = startIndex; i < end;)
            {
                for (; i < end; i++)
                {
                    char current = sb[i];

                    if (char.IsLetterOrDigit(current))
                    {
                        _odd = true;
                        _hash1 = ((_hash1 << 5) + _hash1 + (_hash1 >> 27)) ^ char.ToUpperInvariant(current);
                        i++;

                        // Hash next character:
                        for (; i < end; i++)
                        {
                            char next = sb[i];

                            if (char.IsLetterOrDigit(next))
                            {
                                _odd = false;
                                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(next);
                                i++;
                                break;
                            }
                        }

                        break;
                    }
                }
            }
        }
    }

#else

    private void DoAdd(StringBuilder builder, int startIndex, int count)
    {
        if (count == 0)
        {
            return;
        }

        int chunkStart = 0;

        foreach (ReadOnlyMemory<char> chunk in builder.GetChunks())
        {
            if (startIndex >= chunkStart + chunk.Length)
            {
                chunkStart += chunk.Length;
                continue;
            }

            int spanStart = startIndex - chunkStart;
            ReadOnlySpan<char> span = chunk.Span.Slice(spanStart, Math.Min(chunk.Length - spanStart, count));
            Add(span);

            if (count == span.Length)
            {
                break;
            }

            count -= span.Length;
            chunkStart += chunk.Length;
            startIndex = chunkStart;
        }
    }

#endif

    private void GetHashCodeOrdinal(ReadOnlySpan<char> span)
    {
        Debug.Assert(span.Length > 0);

        unchecked
        {
            if (_odd)
            {
                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ span[0];
                _odd = false;
                span = span.Slice(1);
            }

            for (int i = 0; i < span.Length; i += 2)
            {
                _hash1 = ((_hash1 << 5) + _hash1 + (_hash1 >> 27)) ^ span[i];

                if (i == span.Length - 1)
                {
                    _odd = true;
                    break;
                }

                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ span[i + 1];
            }
        }
    }

    private void GetHashCodeOrdinalIgnoreCase(ReadOnlySpan<char> span)
    {
        Debug.Assert(span.Length > 0);

        unchecked
        {
            if (_odd)
            {
                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(span[0]);
                _odd = false;
                span = span.Slice(1);
            }

            for (int i = 0; i < span.Length; i += 2)
            {
                _hash1 = ((_hash1 << 5) + _hash1 + (_hash1 >> 27)) ^ char.ToUpperInvariant(span[i]);

                if (i == span.Length - 1)
                {
                    _odd = true;
                    break;
                }

                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(span[i + 1]);
            }
        }
    }

    private void GetHashCodeAlphaNumericNoCase(ReadOnlySpan<char> span)
    {
        Debug.Assert(span.Length > 0);

        unchecked
        {
            if (_odd)
            {
                for (int i = 0; i < span.Length; i++)
                {
                    char c = span[i];

                    if (char.IsLetterOrDigit(c))
                    {
                        _odd = false;
                        _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(c);
                        span = span.Slice(i + 1);
                        break;
                    }
                }
            }

            for (int i = 0; i < span.Length;)
            {
                for (; i < span.Length; i++)
                {
                    char current = span[i];

                    if (char.IsLetterOrDigit(current))
                    {
                        _odd = true;
                        _hash1 = ((_hash1 << 5) + _hash1 + (_hash1 >> 27)) ^ char.ToUpperInvariant(current);
                        i++;

                        // Hash next character:
                        for (; i < span.Length; i++)
                        {
                            char next = span[i];

                            if (char.IsLetterOrDigit(next))
                            {
                                _odd = false;
                                _hash2 = ((_hash2 << 5) + _hash2 + (_hash2 >> 27)) ^ char.ToUpperInvariant(next);
                                i++;
                                break;
                            }
                        }

                        break;
                    }
                }
            }
        }
    }
}
